server:
  port: 8080

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://syh80882.cafe24.com/syh80882
    username: syh80882
    password: abc123!@
    sql-script-encoding: utf-8
  messages:
    basename: messages/messages, messages/error

  jpa:
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: false
        format_sql: true
        default_batch_fetch_size: 1000
    open-in-view: false

logging:
  level:
    org:
      hibernate:
      type: trace
app:
  oauth:
    jwt:
      public-key: -----BEGIN PUBLIC KEY-----
        MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAj1PhKA5qWltkVczEeYaF
        4rdOqppgWEGHKVKBRblJfTorEywumd/pIfWMrHQQWFQKsnTmshVZozKEvt3QKtnY
        DLdCqijdupIDgHHQ1dD7X/AnooJbsCm1uXDcPoGc1QH4S+xUskczns0aiGWFyeZ5
        28+mmS0OquA9wrxuT7qZd4OcdbNTk4t89kYMz1hTjXM7TL+gYQo1w1kswFFXOnSA
        ETVjyzHL+STsR5uyAFMHTI2zI7Y1Dr3IUceimH19IKoFG4V+ovJZ4YakRlB5OutH
        VfWovNnJh5x60Q1CcjRmp4u0onaJ2/Z3yf4t4lZHFy233Ttl7QajUaE1EDXy+Jqk
        nwIDAQAB
        -----END PUBLIC KEY-----

      expirationInMs: 604800000

jwt:
  secretKey: testtesttesttesttest42fwef234132412wqdfqwf12
  refreshKey: testtesttesttesttest42fwef234132412wqdfqwf12vvdsvsd
  signatureAlgorithm: HS256
  accessTokenExpired: 604800
  refreshTokenExpired: 6048000



environments:
  server-url: http://127.0.0.1